#!/usr/bin/env bash
# Installs nginx server

sudo apt-get update -y
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Holberton School :)" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
